import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HomeNavigation from "@/ui/HomeNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HomeNavigation></HomeNavigation>
        {children}
        <footer className=" h-96">
          something
        </footer>
      </body>
    </html>
  );
}
